name: File Census
on: [push, pull_request, workflow_dispatch]
jobs:
  run-census:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List files; update service worker
        run: python3 list.py
      - name: Commit & push
        run: bash push.sh
        env:
          token: ${{ secrets.GITHUB_TOKEN }}